# Site settings
title: kipper
email: hello@seasalt.io
description: Professional developers and marketers use Kipper to make beautiful iOS App Store screenshots.
baseurl: ""
url: "http://getkipper.com"
twitter_username: getkipper
app_url: "https://itunes.apple.com/app/kipper/"

# Build settings
markdown: redcarpet
highlighter: pygments

exclude:
  - '*.haml'
  - '*.rb'
  - '*.coffee'
  - '*.yml'
  - '.fontcustom-manifest.json'
  - 'Guardfile'
  - 'Procfile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Readme.md'
  - 'bower_components'
  - 'node_modules'
  - 'gulpfile.js'
  - 'package.json'
