# Site settings
title: Kipper
email: hello@seasalt.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kipper.com" # the base hostname & protocol for your site
twitter_username: kipper
github_username:  seasaltio

# Build settings
markdown: redcarpet
highlighter: pygments

exclude:
  - '*.haml'
  - '*.rb'
  - '*.coffee'
  - '*.yml'
  - '.fontcustom-manifest.json'
  - 'Guardfile'
  - 'Procfile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Readme.md'
  - 'bower_components'
  - 'node_modules'
  - 'gulpfile.js'
  - 'package.json'
